// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3707.RealSwerveShady;

import org.usfirst.frc3707.RealSwerveShady.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick joystick0;
    public JoystickButton a;
    public JoystickButton y;
    public JoystickButton x;
    public Joystick joystick1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(1);
        
        x = new JoystickButton(joystick1, 3);
        x.whileHeld(new auto_lift_moveToMiddle());
        y = new JoystickButton(joystick1, 4);
        y.whileHeld(new auto_lift_moveToHigh());
        a = new JoystickButton(joystick1, 1);
        a.whileHeld(new auto_lift_moveToLow());
        joystick0 = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("joystick_claw_inAndOut", new joystick_claw_inAndOut());
        SmartDashboard.putData("joystick_drive_swerve", new joystick_drive_swerve());
        SmartDashboard.putData("joystick_lift_upAndDown", new joystick_lift_upAndDown());
        SmartDashboard.putData("joystick_winch_hoist", new joystick_winch_hoist());
        SmartDashboard.putData("auto_claw_spitTimed", new auto_claw_spitTimed());
        SmartDashboard.putData("auto_drive_directionTimed", new auto_drive_directionTimed());
        SmartDashboard.putData("auto_lift_moveToMiddle", new auto_lift_moveToMiddle());
        SmartDashboard.putData("auto_lift_moveToLow", new auto_lift_moveToLow());
        SmartDashboard.putData("auto_lift_moveToHigh", new auto_lift_moveToHigh());
        SmartDashboard.putData("auto_action_straightToSwitch", new auto_action_straightToSwitch());
        SmartDashboard.putData("publishSonarReadings", new publishSonarReadings());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getjoystick0() {
        return joystick0;
    }

    public Joystick getjoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

